name: Unittests & Auto-publish

# Allow to trigger the workflow manually (e.g. when deps changes)
on: [push, workflow_dispatch]

jobs:
  pytest-job:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.13']
    runs-on: ubuntu-latest
    timeout-minutes: 30

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.python-version }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v3

    # Install deps
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - run: pip --version
    - run: pip install --no-cache-dir -e .[dev]
    - run: pip freeze

    # Run tests
    - name: Run core tests
      run: pytest -vv -n auto

  # TODO(klausg): Add publish job to push to PyPI later